service: AWSRekoginitionWhatsAppIntegration


provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rekognition:RecognizeCelebrities
      Resource: "*"
  profile: ${file(./config/config.${self:provider.stage}.json):serverless.profile}
  region: ap-south-1
  stage: dev


functions:
  httpWebHooktoTwilioURL:
    handler: handler.httpWebHooktoTwilioURL
    events:
    - http:
        path: response
        method: post
        integration: lambda
        response:
          headers:
            Content-Type: "'text/xml'"
          template: $input.path("$")
          statusCodes:
            200:
              pattern: ''
              template:
                application/json: $input.path("$")
              headers:
                Content-Type: "'text/xml'"

plugins:
  - serverless-python-requirements
